export ZPLUG_HOME="$HOME/.zplug"
if [[ ! -d "$HOME/.zplug" ]]
then
   git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

source ~/.zplug/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/pyenv", from:oh-my-zsh
zplug "plugins/sdk", from:oh-my-zsh
zplug "plugins/kubectl", from:oh-my-zsh
zplug "themes/theunraveler", from:oh-my-zsh, as:theme
zplug "zsh-users/zsh-autosuggestions"
zplug "lukechilds/zsh-nvm"

# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

# Load Plugins
zplug load

[ ! -d "$HOME/.sdkman" ] && curl -s "https://get.sdkman.io" | bash
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

[ -s "$HOME/.artifactory/creds.sh" ] && \. "$HOME/.artifactory/creds.sh"

[ -s "$HOME/.boot/creds.sh" ] && \. "$HOME/.boot/creds.sh"

[ -s "$HOME/.aws/creds.sh" ] && \. "$HOME/.aws/creds.sh"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

alias ec="$EDITOR $HOME/.zshrc"
alias sc="source $HOME/.zshrc"
