# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="theunraveler"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(nvm tmux tmuxinator brew docker-compose kubectl git)

# User configuration
export PATH="$USER_BASE_PATH/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:$PATH"
export AWS_REGION=us-east-1
source $ZSH/oh-my-zsh.sh
if ! [ -z "$(command -v pyenv)" ]; then
  eval "$(pyenv init -)"
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export SDKMAN_DIR="/Users/ben.jongbloedt/.sdkman"
[[ -s "/Users/ben.jongbloedt/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/ben.jongbloedt/.sdkman/bin/sdkman-init.sh"

[ -s "$HOME/.artifactory/creds.sh" ] && \. "$HOME/.artifactory/creds.sh"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias mux=tmuxinator
