# Editor
export EDITOR=nvim

[ ! -d "$HOME/.sdkman" ] && curl -s "https://get.sdkman.io" | bash
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
export PATH="$HOME/.cargo/bin:$PATH"
